version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  reservation:
    build:
      context: Reservation
    depends_on:
      - postgres
    ports:
      - "8070:8070"
  payment:
    build:
      context: Payment
    depends_on:
      - postgres
    ports:
      - "8060:8060"
  loyalty:
    build:
      context: Loyalty
    depends_on:
      - postgres
    ports:
      - "8050:8050"
  gateway:
    build:
      context: Gateway
    ports:
      - "8080:8080"
    depends_on:
      - reservation
      - payment
      - loyalty

volumes:
  db-data: